### ISSUE TITLE
Need more translations

### ISSUE THREAD

**Issue by Tostino** [GoSimpleLLC/nbvcxz#11]
I'd love to have nbvcxz translated into as many languages as possible.  Currently, it's got an English and French translation.  I sadly am not multilingual, so I can't really do anything here.  I am hoping some users who are multilingual can take a little bit of time to translate the not terribly large amount of text into whatever languages they are able to. 

The two files which need to be translated to another language can be found here: https://github.com/GoSimpleLLC/nbvcxz/blob/master/src/main/resources/feedback.properties
and here: https://github.com/GoSimpleLLC/nbvcxz/blob/master/src/main/resources/main.properties

Edit: We have had some translations completed already, so i'll list them here.
French
Russian
Ukrainian
Afrikaans
Hungarian
Spanish
Portuguese

If you know the language, feel free to review each: https://github.com/GoSimpleLLC/nbvcxz/tree/master/src/main/resources

**Comment by scadgek** [comment]
I could translate to russian and ukrainian.

**Comment by Tostino** [comment]
@scadgek That would be very appreciated!

**Comment by Tostino** [comment]
![image](https://cloud.githubusercontent.com/assets/8227578/24074402/2849670e-0bde-11e7-89b8-6e2544b6fd25.png)
There we go, we now have support for Russian.

**Comment by scadgek** [comment]
@Tostino thanks for the screenshot, I see I misunderstood some wordings - will patch it now :)

**Comment by Tostino** [comment]
@scadgek in English I didn't bother doing singular of any time values. It's a little weird in English to say "1 seconds" too, but it was simpler than having to deal with changing between singular and plural based on the value.

**Comment by svzdvd** [comment]
I can translate to Italian...

**Comment by Tostino** [comment]
@svzdvd Would love to have an Italian translation.

**Comment by Tostino** [comment]
Is there anyone who could do a Spanish translation? That is one I was really hoping to support.

**Comment by vfspirit** [comment]
I could do a Hungarian translation if you want.

**Comment by Tostino** [comment]
@vfspirit Sounds good, would appreciate it.

**Comment by vfspirit** [comment]
There are a few lines that could be translated either as formal or informal. Which one should I prefer?

**Comment by Tostino** [comment]
@vfspirit Informal is fine. I just merged.

Appreciate it.

**Comment by Tostino** [comment]
I want to thank @everyone who contributed their help with translating.  I have just released version [1.4.0](https://github.com/GoSimpleLLC/nbvcxz/releases/tag/1.4.0) which now supports all of the languages you have helped contribute.
