### ISSUE TITLE
L33t words not matched as expected

### ISSUE THREAD

**Issue by jdhoek** [GoSimpleLLC/nbvcxz#28]
L33tified words seem to get only partial dictionary matches.

### Result

The password `Ch1ck3n1970` currently yields:

* `BruteForceMatch`: `C`
* `BruteForceMatch`: `h`
* `BruteForceMatch`: `1`
* `BruteForceMatch`: `c`
* `DictionaryMatch`: `ken` (`male_names`)
* `YearMatch`: `1970`

For comparison, this is `Chicken1970`:

* `DictionaryMatch`: `chicken` (`passwords`)
* `YearMatch`: `1970`

### Expected

For `Ch1ck3n1970` I would expect the same matches as `Chicken1970`:

* `DictionaryMatch`: `chicken` (`passwords`, Leet Substitutions `true`)
* `YearMatch`: `1970`

**Comment by Tostino** [comment]
Yup, that for sure looks like an issue and it wasn't caught by the test cases.  I'll take a look into that shortly.

**Comment by Tostino** [comment]
Found the issue, working on a fix now.  My un-leet code was not as robust as the code in zxcvbn.  I'll fix that right up shortly.

**Comment by Tostino** [comment]
Alright, I fixed this issue in the commit referenced above.  Please let me know if you find any additional issues with it.

**Comment by jdhoek** [comment]
Nice. I'll see if I can reproduce this Monday. Looking at the commit it looks you fixed it though.

**Comment by jdhoek** [comment]
Works for me now. :+1:
