### ISSUE TITLE
Release new version containing german translations

### ISSUE THREAD

**Issue by wwerner** [GoSimpleLLC/nbvcxz#36]
I saw that german translations were brought in by @sgwerder with  7b954fde10b0eb224e43c155e7ef2b822f4ce721.

The released version 1.4.0 on maven central does not yet contain these. It would be great if you'd make a new release.

In the meantime, if anyone stumbles upon this, pulling via http://jitpack.io works:
````
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>
<dependencies>
  <dependency>
    <groupId>com.github.GoSimpleLLC</groupId>
    <artifactId>nbvcxz</artifactId>
    <version>7b954fde10b0eb224e43c155e7ef2b822f4ce721</version> <!-- this is the same code as 1.4.0, but with german translations -->
  </dependency>
</dependencies>
````
Thanks for the great work!

**Comment by Tostino** [comment]
I was planning on pushing up a new release this week actually.  I'll let you know when done.

Glad you like the library!

**Comment by Tostino** [comment]
Alright, release is pushed out to Maven, and also created a corresponding release here on GitHub.
