### ISSUE TITLE
Very long passwords passed in for estimation can cause slowness

### ISSUE THREAD

**Issue by Tostino** [GoSimpleLLC/nbvcxz#43]
It was noted in this discussion that if a extremely long password was passed in, it could cause issues with performance.
https://github.com/7ep/demo/commit/c5671bc40a084f4de0728c9017636f8bdc618ae7#commitcomment-32260369

Implement a max length configuration which will have a sane default (like 72 characters to match bcrypt's max length for example), and truncate any characters after that. Return feedback that the max length was hit if that was the case.

**Comment by svschouw-bb** [comment]
The main (or first?) issue seems to be with the `DateMatcher.matchDatesWithSeparator(...)` which seems to be quadratic. It produces all possible subsequences of the password. I'm not exactly sure why it does this. Why not just use `Matcher.find(...)` ?

**Comment by Tostino** [comment]
I have implemented a maxLength configuration with a default length of 72 characters.

commit: c387d543
