### ISSUE TITLE
Define a stable automatic module name

### ISSUE THREAD

**Issue by eckig** [GoSimpleLLC/nbvcxz#46]
nbvcxz does not currently use modules. When we use it in a JDK9 modular application, Java turns the JAR into a so-called automatic module, whose name is derived from the file name. However, the default name does not follow the recommended module naming conventions (reverse-dns style, module name derived from the main exported package).

It is possible to specify a stable automatic module name through a Automatic-Module-Name manifest entry, while still targeting JDK8:

`Automatic-Module-Name: me.gosimple.nbvcxz`

Selecting a stable module name is very important, because Java does not allow two modules to own the same package. So either provide the module name through the manifest file or event better: Provide a complete module declaration.

**Comment by Tostino** [comment]
Thank you for the feedback.

I added the automatic module name to the pom in commit: 2f7e1883c15e844193e79af5090070ffa3730d9b

I confirmed it is in the manifest.mf

I've not worked on any modularized projects yet, so a full module declaration would be great but I am not sure when I will have the time to learn how to do so. If you have any pointers or have worked on modularized projects before i'd love to hear.

**Comment by eckig** [comment]
Sorry for the late reply... Unfortunately, the automatic module name is not present in the JAR file I just retrieved from maven.


I you want to provide a `module-info.java` you can start with this one as a baseline:

```
module me.gosimple.nbvcxz
{

    exports me.gosimple.nbvcxz;
    exports me.gosimple.nbvcxz.scoring;
}
```

Basically you just list all the packages that third parties (like me) are allowed to access with `exports` and if you depend on other modules you list them with `requires`.

**Comment by Tostino** [comment]
Working on this now, will have a new release in probably a week.

**Comment by Tostino** [comment]
And, still haven't done a release. Apologies, but it just hasn't been possible for me to focus on for more than a few min. This will be closed once the next release happens.

**Comment by Tostino** [comment]
Closed due to release 1.5.0

**Comment by eckig** [comment]
Works, thanks 👍

**Comment by Tostino** [comment]
@eckig Glad to hear it, sorry for the long delay in getting a release out.
