### ISSUE TITLE
High deviation for a certain password

### ISSUE THREAD

**Issue by thomas-mc-work** [GoSimpleLLC/nbvcxz#59]
Regarding this password: `Submit new password`

- on [the web demo](https://lowe.github.io/tryzxcvbn/) I get a score of `4` and a guesses count of `212200000000` (guesses_log10: 11.32675)
- with this library I get a score of `2` and a guesses count of `48909168`

Setup:

- Same small additional user dictionary
- `PasswordMatcher` removed from the matchers list
- Version: `1.5.0`

I saw in the Readme that there are differences between the two versions. But this one seems to be very different. Is there a way for me to achieve results that are as close as possible? I'm using both libraries for validation. I come into a bad situation telling the user in the frontend that the password strength is good. But after submitting the server says that it's not.

**Comment by Tostino** [comment]
So without disabling the password matcher, I can see where we have some differences.

Here is the output with just the default settings from nbvcxz:

```
> java -jar .\nbvcxz-1.5.0.jar
Commands: estimate password (e); generate password (g); quit (q)
Please enter your command:
e
Please enter the password to estimate:
Submit new password
----------------------------------------------------------
Time to calculate: 75 ms
Password: Submit new password
Entropy: 22.098669538287247
Your password does not meet the minimum strength requirement.
Warning: This is a top-10 common password.
Suggestion: Add another word or two. Uncommon words are better.
Suggestion: Capitalization doesn't help very much.
Time to crack: ONLINE_THROTTLED: 25 days
Time to crack: ONLINE_UNTHROTTLED: 12 hours
Time to crack: OFFLINE_BCRYPT_14: 36 minutes
Time to crack: OFFLINE_BCRYPT_12: 9 minutes
Time to crack: OFFLINE_BCRYPT_10: 2 minutes
Time to crack: OFFLINE_BCRYPT_8: 33 seconds
Time to crack: OFFLINE_BCRYPT_5: 4 seconds
Time to crack: OFFLINE_SHA512: instant
Time to crack: OFFLINE_SHA1: instant
Time to crack: OFFLINE_MD5: instant
-----------------------------------
Match Type: DictionaryMatch
Entropy: 10.647458426454921
Token: Submit
Start Index: 0
End Index: 5
Length: 6
Dictionary: english
Dictionary Value: submit
Rank: 802
Length: 6
Leet Substitutions: false
Reversed: false
Distance: 0
-----------------------------------
Match Type: SeparatorMatch
Entropy: 3.3219280948873626
Token:
Start Index: 6
End Index: 6
Length: 1
-----------------------------------
Match Type: DictionaryMatch
Entropy: 3.8073549220576037
Token: new
Start Index: 7
End Index: 9
Length: 3
Dictionary: english
Dictionary Value: new
Rank: 14
Length: 3
Leet Substitutions: false
Reversed: false
Distance: 0
-----------------------------------
Match Type: SeparatorMatch
Entropy: 3.3219280948873626
Token:
Start Index: 10
End Index: 10
Length: 1
-----------------------------------
Match Type: DictionaryMatch
Entropy: 1.0
Token: password
Start Index: 11
End Index: 18
Length: 8
Dictionary: passwords
Dictionary Value: password
Rank: 2
Length: 8
Leet Substitutions: false
Reversed: false
Distance: 0
----------------------------------------------------------
```

So I see that the "submit" match has a much higher rank in our dictionary than it does in the zxcvbn dictionary. That's the main difference in the scoring for this example. 

It seems like it would be useful to provide a "zxcvbn compatibility mode" which ensures we use the same dictionaries with everything ranked exactly the same, disable any extra features zxcvbn doesn't support, etc. Until someone provides a PR that works in that direction, or I get time to do it - the workaround:
You'll need to manually configure the dictionaries to be the same as the ones used by zxcvbn, not using the default dictionaries.  You can also disable Levenshtein distance to get closer results to zxcvbn.

**Comment by thomas-mc-work** [comment]
Thank you!
