### ISSUE TITLE
English wordlist too short / not original zxcvbn list?

### ISSUE THREAD

**Issue by cyb3rko** [GoSimpleLLC/nbvcxz#61]
Hey there,
thanks for rewriting this awesome library for java.

Is there a reason why [english.txt](https://github.com/GoSimpleLLC/nbvcxz/blob/master/src/main/resources/dictionaries/english.txt) "only" contains 18,091 while the zxcvbn [english_wikipedia.txt](https://github.com/dropbox/zxcvbn/blob/master/data/english_wikipedia.txt), which obviously party contains the same entries, has 100,000 lines?

Otherwise I could open a pull request to fix this.

Greetings!

**Comment by Tostino** [comment]
That is a good question, and at this point I cannot remember... So i'd say a pull request is in order.

**Comment by Tostino** [comment]
I'm going to close this at this point. The word list was intentionally shortened to give better results after analyzing the overall mis-matching that happens when you have so many short words that match entirely within other words (a, is, i, etc...).
