### ISSUE TITLE
Wrong entropy computing

### ISSUE THREAD

**Issue by Zhenyria** [GoSimpleLLC/nbvcxz#73]
I use **1.5.0** version of the library.

I use Nbvcxz for entropy calculating and i configure it with the follow way:
```
private static final double MIN_ENTROPY = 27d;
private static final Nbvcxz nbvcxz;

static {
    List<Dictionary> dictionaryList = ConfigurationBuilder.getDefaultDictionaries();

    Configuration configuration =
        new ConfigurationBuilder()
            .setLocale(Locale.forLanguageTag("ru"))
            .setMinimumEntropy(MIN_ENTROPY)
            .setDictionaries(dictionaryList)
            .createConfiguration();

    nbvcxz = new Nbvcxz(configuration);
  }
```

Then i try to get entropy of a password:
```
double currentEntropy = nbvcxz.estimate(password).getEntropy();
```

So, when i try to check password `A2013n2000` i get  `22.11254640984653`. And when i check password `A2013n200` (the same but without last 0) i get `36.54152973076582`

I think that it is some error. Why more difficult password has less entropy?

**Comment by Tostino** [comment]
In the 1st instance, we have two numbers that will be recognized as common years and thus scored quite low. In the 2nd instance, the fact that only one of those sets of numbers is found to be a common year is why it's got a higher score even with a slightly shorter length.

We are assuming the password cracker will try combinations of common things before moving on to more brute force methods.

This isn't an actual issue, so i'll be closing this.
