### ISSUE TITLE
Program fails if maintainer is hit by a bus

### ISSUE THREAD

**Issue by okiyama** [GoSimpleLLC/nbvcxz#9]
[The latest release](https://github.com/GoSimpleLLC/nbvcxz/releases/tag/1.3.4) serves primarily to bump up the default hashing speed. If the maintainer is hit by a bus (or, less likely loses interest in the project) it'd be good to have an option that automatically bumps this variable up based on Moore's law.

It'll be less accurate than a human-approved value, but more future proof.

**Comment by Tostino** [comment]
I love the idea, and added support for it in: 4e9bf262b15aae190ef863d7a69455ba736eaf81

Let's hope this gets the most use because people forget to upgrade to later versions, rather than me getting hit by a bus :).
